/*
 * RakuRaku IME - EZ Input Method for Android
 * Copyright (C) 2026  RakuRaku IME Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

package org.ghostsinthelab.app.rakurakuime.data

/**
 * Suggests EZ root-keystroke strings for a phrase the user is adding via
 * the User Phrase Manager, faithful to the 輕鬆輸入法 取碼規則
 * documented at
 * <https://github.com/hiroshiyui/EzIM_Tables_Project/blob/main/CLAUDE.md>.
 *
 * **Per-phrase length rule**
 *
 * | 字數 | 取碼方式 | 碼數 |
 * |---|---|---|
 * | 1   | 第一字「頭」+「尾」（整組編碼） | 1 或 2 |
 * | 2   | 第一字整組 + 第二字整組         | 2 至 4 |
 * | 3   | 三字皆取「頭」                  | 3      |
 * | 4   | 四字皆取「頭」                  | 4      |
 * | 5+  | 前四字取「頭」（其餘忽略）      | 4      |
 *
 * "頭" = the first key of the chosen encoding; "尾" = the remainder
 * (often the second key, but for a single-key encoding the head and
 * tail collapse to the same key — so the full encoding is just one
 * key, not two).
 *
 * **Per-character encoding selection** (when a char has multiple rows):
 *  1. Prefer a length-1 encoding (single root key).
 *  2. Else prefer a non-all-digit encoding.
 *  3. Else the encoding that appears first in the CIN file.
 *
 * **Output ordering**
 *
 * The list returned starts with the strict canonical answer (the EZ
 * rule resolves to exactly one string) and is followed by alternates
 * generated by trying other valid encodings at each position. Distinct
 * results only, capped at [totalLimit]. Any character missing from the
 * corpus collapses the whole result to empty so the caller can fall
 * back to manual entry.
 */
object EzKeystrokeLookup {

    private const val MAX_PHRASE_KEY_CHARS = 4

    suspend fun suggest(
        phrase: String,
        dao: DictionaryDao,
        totalLimit: Int = 10,
    ): List<String> {
        if (phrase.isEmpty()) return emptyList()
        if (totalLimit <= 0) return emptyList()

        val take = phrase.take(MAX_PHRASE_KEY_CHARS)

        // Per-char encodings in CIN-file order. Empty for any one char ⇒
        // bail out: a partial answer would be a lie.
        val perCharRaw: List<List<String>> = take.map { ch ->
            val raw = dao.encodingsForCharacter(ch.toString())
            if (raw.isEmpty()) return emptyList()
            sortByEzPickingRule(raw)
        }

        // Apply the phrase-length rule to extract the per-position
        // contribution(s). For 1- and 2-char phrases each position
        // contributes the full encoding (possibly 1 or 2 keys); for
        // 3+ char phrases each contributes just the "頭" (first key
        // of the chosen encoding), de-duplicated.
        val contributions: List<List<String>> = if (take.length <= 2) {
            perCharRaw
        } else {
            perCharRaw.map { encs -> encs.map { it.first().toString() }.distinct() }
        }

        val seen = LinkedHashSet<String>()
        dfs(contributions, 0, StringBuilder(), seen, totalLimit)
        return seen.toList()
    }

    private fun dfs(
        perPos: List<List<String>>,
        index: Int,
        acc: StringBuilder,
        out: MutableSet<String>,
        limit: Int,
    ) {
        if (out.size >= limit) return
        if (index == perPos.size) {
            out.add(acc.toString())
            return
        }
        for (option in perPos[index]) {
            if (out.size >= limit) return
            val saved = acc.length
            acc.append(option)
            dfs(perPos, index + 1, acc, out, limit)
            acc.setLength(saved)
        }
    }

    /**
     * Order [encodings] by the EZ per-character picking rule so the first
     * element is the strict canonical pick; subsequent elements are the
     * remaining options in the rule's preference order. Stable: ties from
     * the caller's input order are preserved.
     */
    internal fun sortByEzPickingRule(encodings: List<String>): List<String> {
        if (encodings.size <= 1) return encodings
        val single = ArrayList<String>(2)
        val nonDigit = ArrayList<String>(encodings.size)
        val digitOnly = ArrayList<String>(2)
        for (enc in encodings) {
            when {
                enc.length == 1 -> single.add(enc)
                enc.all { it.isDigit() } -> digitOnly.add(enc)
                else -> nonDigit.add(enc)
            }
        }
        return single + nonDigit + digitOnly
    }
}
